version: '3.8'

services:
  # minerva-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mysql-db

  mysql-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: minerva
      MYSQL_USER: root
      MYSQL_PASSWORD: test123
    ports:
      - "3307:3307"
